[[plugins]] # Dark powered Vim/Neovim plugin manager
repo = 'Shougo/dein.vim'

[[plugins]] # Interactive command execution in Vim.
repo = 'Shougo/vimproc.vim'

  [plugins.build]
# windows = 'tools\\update-dll-mingw'
  win32   = 'nmake -f make_msvc32.mak'
  win64   = 'nmake -f make_msvc64.mak'
  cygwin  = 'make -f make_cygwin.mak'
  mac     = 'make -f make_mac.mak'
  linux   = 'make'
  unix    = 'gmake'

[[plugins]] # eskk aims to provide powerful input method platform in Vim.
repo = 'tyru/eskk.vim'

[[plugins]] # Powerful file explorer implemented by Vim script
repo = 'Shougo/vimfiler.vim'
depends = ['unite.vim']

[[plugins]] # Align Them All!
repo = 'h1mesuke/vim-alignta'

[[plugins]] # fugitive.vim: a Git wrapper so awesome, it should be illegal
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]] # rails.vim: Ruby on Rails power tools
repo = 'tpope/vim-rails'

[[plugins]] # Run Rspec specs from Vim
repo = 'thoughtbot/vim-rspec'

#-------------------------------------------------------------------------------
# Unite
#-------------------------------------------------------------------------------
# Unite and create user interfaces
[[plugins]]
repo = 'Shougo/unite.vim'

# outline source for unite.vim
[[plugins]]
repo = 'Shougo/unite-outline'

# tags soruce for unite.vim
[[plugins]]
repo = 'tsukkee/unite-tag'

[[plugins]]
repo = 'osyo-manga/unite-quickfix'

[[plugins]] # A unite.vim plugin
repo = 'ujihisa/unite-colorscheme'

[[plugins]] # Unite source for git conflicts.
repo = 'moznion/unite-git-conflict.vim'

[[plugins]] #  vim-unite-watson.vim is the unite source for watson.
repo   = 'alpaca-tc/vim-unite-watson.vim'
on_cmd = 'Watson'

[[plugins]] # a unite.vim plugin for rails
repo = 'basyura/unite-rails'

[[plugins]]
repo = 'iyuuya/unite-rails-fat'

#-------------------------------------------------------------------------------
# ColorScheme
#-------------------------------------------------------------------------------
[[plugins]] # A dark colour scheme for Vim & gVim
repo = 'w0ng/vim-hybrid'

[[plugins]] # A colorful, dark color scheme for Vim.
repo = 'nanotech/jellybeans.vim'

[[plugins]] # Molokai color scheme for Vim
repo = 'tomasr/molokai'

[[plugins]] # Tomorrow Theme for Vim
repo = 'chriskempson/vim-tomorrow-theme'

[[plugins]] # Wombat for 256 color xterms
repo = 'vim-scripts/wombat256.vim'

#-------------------------------------------------------------------------------
# ToDo
#-------------------------------------------------------------------------------
[[plugins]] # A Vim plugin which shows a git diff in the gutter (sign column) and stages/reverts hunks.
repo = 'airblade/vim-gitgutter'

[[plugins]] # repeat.vim: enable repeating supported plugin maps with '.'
repo = 'tpope/vim-repeat'

[[plugins]] # abolish.vim: easily search for, substitute, and abbreviate multiple variants of a word
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'thinca/vim-template'

[[plugins]] # Realtime preview by Vim. (Markdown, reStructuredText, textile)
repo = 'kannokanno/previm'

[[plugins]]
repo = 'vim-scripts/dbext.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]] # Integrated reference viewer.
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'lambdalisue/vim-gista'

[[plugins]] # Run commands quickly.
repo = 'thinca/vim-quickrun'
depends = 'quickrunex-vim'

[[plugins]] # Async syntax checking.
repo = 'osyo-manga/vim-watchdogs'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]] # Syntax checking hacks for vim
repo = 'scrooloose/syntastic'

[[plugins]] # Highlight quickfix errors
repo = 'jceb/vim-hier'

[[plugins]] # See quickfix, location list and Syntastic lists errors and warnings as you move through a vim file.
repo = 'dannyob/quickfixstatus'

[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]] # surround.vim: quoting/parenthesizing made simple
repo = 'tpope/vim-surround'

[[plugins]] # emmet for vim: http://emmet.io/
repo = 'mattn/emmet-vim'

[[plugins]] # The Vim RuboCop plugin runs RuboCop and displays the results in Vim
repo = 'ngmy/vim-rubocop'

[[plugins]] # sophisticated comment plugin http://www.vim.org/scripts/script.php?script_id=2554
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'basyura/bitly.vim'

[[plugins]]
repo = 'mattn/favstar-vim'

[[plugins]]
repo = 'basyura/TweetVim'
depends = ['open-browser.vim', 'twibill.vim', 'bitly.vim', 'webapi-vim', 'favstar-vim']

[[plugins]]
repo = 'basyura/J6uil.vim'

[[plugins]]
repo = 'vim-jp/vital.vim'

[[plugins]]
repo = '5t111111/alt-gtags.vim'

[[plugins]]
repo = 'szw/vim-tags'

# " vim: fdm=marker ft=vim
